version: '3'

services:
    db:
      container_name: agenda
      image: mysql:latest
      environment:
         MYSQL_ROOT_PASSWORD: xyzt370
         MYSQL_DATABASE: agenda
         MYSQL_USER: admin
         MYSQL_PASSWORD: xyzt370
      ports:
        - "3306:3306"
      volumes:
      - ./dbDocker:/docker-entrypoint-initdb.d
      networks:
      - test
      

    webapp:
      container_name: agenda_web
      build: .
      depends_on:
        - db
      ports:
        - "8080:8080"
      links:
        - db
      networks:
        - test
      
networks:
    test:
        driver: "bridge"